---
language: node_js
node_js:
- 10

addons:
  firefox: latest

install:
  - yarn

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - npm run lint:hbs
  - npm run lint:js
  - npm test

branches:
  only:
  - master
